// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: geoservice.proto

package grpcgeoservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Geocode_GetAddress_FullMethodName = "/grpcgeoservice.Geocode/GetAddress"
	Geocode_GetGeocode_FullMethodName = "/grpcgeoservice.Geocode/GetGeocode"
)

// GeocodeClient is the client API for Geocode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeocodeClient interface {
	GetAddress(ctx context.Context, in *Request, opts ...grpc.CallOption) (*AddressListResponse, error)
	GetGeocode(ctx context.Context, in *Request, opts ...grpc.CallOption) (*AddressListResponse, error)
}

type geocodeClient struct {
	cc grpc.ClientConnInterface
}

func NewGeocodeClient(cc grpc.ClientConnInterface) GeocodeClient {
	return &geocodeClient{cc}
}

func (c *geocodeClient) GetAddress(ctx context.Context, in *Request, opts ...grpc.CallOption) (*AddressListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressListResponse)
	err := c.cc.Invoke(ctx, Geocode_GetAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocodeClient) GetGeocode(ctx context.Context, in *Request, opts ...grpc.CallOption) (*AddressListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressListResponse)
	err := c.cc.Invoke(ctx, Geocode_GetGeocode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeocodeServer is the server API for Geocode service.
// All implementations must embed UnimplementedGeocodeServer
// for forward compatibility.
type GeocodeServer interface {
	GetAddress(context.Context, *Request) (*AddressListResponse, error)
	GetGeocode(context.Context, *Request) (*AddressListResponse, error)
	mustEmbedUnimplementedGeocodeServer()
}

// UnimplementedGeocodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeocodeServer struct{}

func (UnimplementedGeocodeServer) GetAddress(context.Context, *Request) (*AddressListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddress not implemented")
}
func (UnimplementedGeocodeServer) GetGeocode(context.Context, *Request) (*AddressListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeocode not implemented")
}
func (UnimplementedGeocodeServer) mustEmbedUnimplementedGeocodeServer() {}
func (UnimplementedGeocodeServer) testEmbeddedByValue()                 {}

// UnsafeGeocodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeocodeServer will
// result in compilation errors.
type UnsafeGeocodeServer interface {
	mustEmbedUnimplementedGeocodeServer()
}

func RegisterGeocodeServer(s grpc.ServiceRegistrar, srv GeocodeServer) {
	// If the following call pancis, it indicates UnimplementedGeocodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Geocode_ServiceDesc, srv)
}

func _Geocode_GetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocodeServer).GetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocode_GetAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocodeServer).GetAddress(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocode_GetGeocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocodeServer).GetGeocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geocode_GetGeocode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocodeServer).GetGeocode(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Geocode_ServiceDesc is the grpc.ServiceDesc for Geocode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Geocode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcgeoservice.Geocode",
	HandlerType: (*GeocodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddress",
			Handler:    _Geocode_GetAddress_Handler,
		},
		{
			MethodName: "GetGeocode",
			Handler:    _Geocode_GetGeocode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geoservice.proto",
}
